version: '3.3'
#----------------------------------------------------------
# definicion de la red y rango de ips 
#
# markitos project
#----------------------------------------------------------
networks:
    markitos-apps-network:
        ipam:
            config:
                - subnet: 172.27.10.0/24
services:
    markitos.api:
        user: "1000:1000"
        build: api
        container_name: 'markitos.api'
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ../apps/api/:/var/www/vhosts/markitos/
        extra_hosts:
            - 'mariadb:172.27.10.12'
        hostname: markitos.api
        networks:
            markitos-apps-network:
                ipv4_address: 172.27.10.14

    markitos.frontend:
        user: "1000:1000"
        build: frontend
        container_name: "markitos.frontend"
        restart: always
        ports:
            - 5173:5173
        volumes:
            - ../apps/frontend/:/var/www/vhosts/markitos/
        hostname: markitos.frontend
        extra_hosts:
            - 'markitos.api:172.27.10.14'
        networks:
            markitos-apps-network:
                ipv4_address: 172.27.10.13

    markitos.mariadb:
        build: mariadb
        container_name: 'markitos.mariadb'
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql
        restart: always
        hostname: markitos.mariadb
        networks:
            markitos-apps-network:
                ipv4_address: 172.27.10.12
