version: "3.8"

networks:
  culturadevop-network:
    ipam:
      config:
        - subnet: 172.27.27.0/24

services:
  culturadevop.api:
    build:
      context: ../../apps/api
      dockerfile: ../../cloud/dockerhub/Dockerfile.api
    image: culturadevop.api:0.0.1
    environment:
      - CDN_DIR=cdn/
      - DB_USERNAME=markitos
      - DB_PASSWORD=markitos
      - DB_DATABASE=markitos
      - DB_HOSTNAME=culturadevop.mariadb
      - DB_HOSTPORT=3306
      - MY_DOMAIN=culturadevop.com
    restart: always
    ports:
      - 3000:3000
    hostname: culturadevop.api
    extra_hosts:
      - "culturadevop.mariadb:172.27.27.3"
    networks:
      culturadevop-network:
        ipv4_address: 172.27.27.10

  culturadevop.frontend:
    build:
      context: ../../apps/frontend
      dockerfile: ../../cloud/dockerhub/Dockerfile.frontend
    image: culturadevop.frontend:0.0.1
    environment:
      - VITE_API_ENDPOINT=http://culturadevop.com:3000/api/v1
    ports:
      - 80:5173
    hostname: culturadevop.frontend
    extra_hosts:
      - "culturadevop.api:172.27.27.10"
    networks:
      culturadevop-network:
        ipv4_address: 172.27.27.2

  culturadevop.mariadb:
    build:
      context: ../../docker/mariadb
      dockerfile: ../../cloud/dockerhub/Dockerfile.mariadb
    image: culturadevop.mariadb:0.0.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=markitos
      - MYSQL_USER=markitos
      - MYSQL_PASSWORD=markitos
    volumes:
      - mariadb_data:/var/lib/mysql
    hostname: culturadevop.mariadb
    ports:
      - 3306:3306
    networks:
      culturadevop-network:
        ipv4_address: 172.27.27.3

  culturadevop.jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8888:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    hostname: culturadevop.jenkins
    extra_hosts:
      - "culturadevop.api:172.27.27.10"
      - "culturadevop.frontend:172.27.27.2"
      - "culturadevop.mariadb:172.27.27.3"
    networks:
      culturadevop-network:
        ipv4_address: 172.27.27.4

volumes:
  mariadb_data:
  jenkins_home:
